name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: GardenShop
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      run: docker build -t mygardenapp .

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Check containers
      run: docker ps

    - name: Verify MySQL tables
      run: |
        docker exec $(docker ps -qf "name=db") \
        mysql -uroot -proot -e "USE GardenShop; SHOW TABLES;"

    - name: Tear down
      run: docker-compose down -v
